<a href="https://colab.research.google.com/github/Tin2810/Lab1_21130201_LeCongThanhTin/blob/master/Task_2_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

arr = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.51, 0.34, 0.15]])
print("Input array: \n", arr)
threshold = 0.5
replacement_value = 0.5

arr[arr > threshold] = replacement_value


print("Result array: \n", arr)

Input array: 
 [[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Result array: 
 [[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
